### PR TITLE
Add spacewalk assets to nova wallet

### PR DESCRIPTION
**Pull request by gianfra-t**
Note: This PR is only for internal review and not intended to be merged. 

Closes [Tasks/#257](https://github.com/pendulum-chain/tasks/issues/257).

`CurrencyIdScale` can be obtained by forming any extrinsic call that contains `CurrencyId` in Polkadot.js, which shows the encoding details of the call.

### CODE REVIEW

**Review by ebma — CHANGES_REQUESTED** [review]
Why do we set the `priceId` to "amplitude-chain" and "pendulum-chain"? Does it need to match something, like our runtime name?

Also, the icons should have different colors. If you compare the icons we added to the other ones in the folder, you'll notice the difference. We need to reach out to @pendulum-chain/product again to provide a different coloring for those.

**Comment by gianfra-t** [comment]
About `priceId`, I was wrong since I thought it was regarding the chain where the price originates. 

The fact is that, by looking at other registered assets and comparing, each one of them has it's own id. For instance, Polkadot registered in different chains will have the same `priceId` which is 'polkadot'. For this I would propose we use `spacewalk-{asset_name}` for the spacewalk assets that do not exists. The only id we can reuse seems to be [usd-coin](https://github.com/pendulum-chain/nova-utils/blob/bb9b7261b732acdb2cfaff40fc910da594f5a621/chains/v18/chains_dev.json#L5278).

About the icons, they should all be completely white right?

**Comment by annatekl** [comment]
@gianfra-t the icons should much visually the ones we have in  [here](https://drive.google.com/drive/u/0/folders/1sZcQzoDxT_EUd2wtEJN8ECNzPakfAMs6). Does Nova require to provide white design?

**Comment by ebma** [comment]
> For this I would propose we use spacewalk-{asset_name} for the spacewalk assets that do not exists.

Okay thanks, yes let's go for that 👍 

@annatekl have a look at any svg in [this](https://github.com/pendulum-chain/nova-utils/tree/add-spacewalk-assets-to-nova-wallet/icons/tokens/white) folder and you'll see how the assets are supposed to look like.

**Comment by annatekl** [comment]
@gianfra-t [here](https://drive.google.com/drive/u/0/folders/1sZcQzoDxT_EUd2wtEJN8ECNzPakfAMs6) is the link with the icons

**Comment by gianfra-t** [comment]
@annatekl the last link for the icons has color/black ones. I don't believe they will accept the PR unless they are in white format, like [here](https://github.com/pendulum-chain/nova-utils/tree/add-spacewalk-assets-to-nova-wallet/icons/tokens/white).

**Comment by annatekl** [comment]
@gianfra-t just uploaded [here](https://drive.google.com/drive/u/0/folders/1sZcQzoDxT_EUd2wtEJN8ECNzPakfAMs6). Let me know if its correct now

**Comment by gianfra-t** [comment]
Thanks! Yes to me they are correct. hopefully they will accept it.

**Review by ebma — APPROVED** [review]
Nice, this is ready for the PR to the upstream repo I think.

**Comment by gianfra-t** [comment]
I closed this as the [PR](https://github.com/novasamatech/nova-utils/pull/2627) for the upstream repo was created.

**Pull request closed without merging**
